// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CloudController from "./cloud_controller"
application.register("cloud", CloudController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import UserLocationController from "./user_location_controller"
application.register("user-location", UserLocationController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController )
